
name: ci
on:
  pull_request:

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        ghc: ['8.4.4','8.6.5', '8.8.4','8.10.2']
        cabal: ['latest']
        os: [ubuntu-latest]

    name: ci-${{ matrix.ghc }}

    env:
      CONFIG: "-O0 --enable-tests"

    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-haskell@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - run: cabal update
      - run: cabal clean
      - run: cabal configure $CONFIG
      - run: cabal freeze $CONFIG
      - uses: actions/cache@v2
        with:
          path: |
            ~/cabal.store
            dist-newstyle

          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}
      - run: cabal build
      - run: cabal test
      - run: cabal check
